function paramstruct = plsrii(paramstoconvert,reverse)
% PLSRII translates parameter (channel) names on the LSR into
% easier-to-type nicknames
%
%   2012/07/14  BH

paramnames = { 'FSC-H';'FSC-A';...
    'SSC-H';'SSC-A';...
    'FITC-H';'FITC-A';...
    'PE-H'; 'PE-A';...
    'AmCyan-H'; 'AmCyan-A';...
    'DsRed-H'; 'DsRed-A';...
    'RFP-H'; 'RFP-A';...
    'Pacific Blue-H'; 'Pacific Blue-A';...
    'Fret-H'; 'Fret-A';...
    'PerCP-Cy5-5-H'; 'PerCP-Cy5-5-A';...
    'PerCP-H'; 'PerCP-A';...
    'PE-Cy7-H'; 'PE-Cy7-A';...
    'APC-H'; 'APC-A';...
    'APC-Cy7-H'; 'APC-Cy7-A';...
	'Width';'Time'};

nicknames = {'fsc';'';...
    'ssc';'';...
    'yfp';'';...
    '';'';...
    'cfp';'';...
    'mch';'';...
    '';'';...
    'bfp';'';...
	'';'';...
	'';'';...
	'';'';...
	'';'';...
	'';'';...
	'';'';...
	'';'t'};

if nargin == 0
    % display default conversions
    disp('Default nicknames and parameter names for LSRII:');
    disp({'Nickname','Parameter'});
    disp([nicknames,paramnames]);
else
    % return struct with nickname conversions
    if nargin < 2;
        reverse = false;
    end
    
    paramstruct = struct;
    
    if ~reverse
        % return struct with nicknames -> param names
        if ~isempty(paramstoconvert)
            % find user-supplied nicknames and return conversions
            for c = 1:length(paramstoconvert)
                k = find(strcmp(paramstoconvert{c},nicknames));
                if ~isempty(k)
                    paramstruct.(nicknames{k}) = paramnames{k};
                end
            end
        else
            % use default conversions
            for c = 1:length(nicknames)
                if ~isempty(nicknames{c})
                    paramstruct.(nicknames{c}) = paramnames{c};
                end
            end
        end
    else
        % return struct with param names -> nicknames
        if ~isempty(paramstoconvert)
            % find user-supplied param names and return nicknames
            for c = 1:length(paramstoconvert)
                k = find(strcmp(paramstoconvert{c},nicknames));
                if ~isempty(k)
                    paramstruct.(underscorify(paramnames{k})) = nicknames{k};
                end
            end
        else
            % use default conversions
            for c = 1:length(paramnames)
                if ~isempty(paramnames{c})
                    paramstruct.(underscorify(paramnames{c})) = nicknames{c};
                end
            end
        end
    end
end