function paramstruct = pstrat(paramstoconvert,reverse)
% PSTRAT translates parameter (channel) names on the Stratedigm into
% easier-to-type nicknames
%
%   2012/07/12 JW
paramnames = { 'FSC LogH';'FSC LinH';...
    'SSC LogH';'SSC LinH';...
    'FITC(530/30) LogH';'FITC(530/30) LogA';...
    'AmCyan(530/30) LogH';'AmCyan(530/30) LogA';...
    'PE(B)(586/20) LogH';'PE(B)(586/20) LogA';...
    'PE(Y)(586/20) LogH';'PE(Y)(586/20) LogA';...
    'PETred(615/30) LogH';'PETred(615/30) LogA';...
    'MCherry(615/30) LogH';'MCherry(615/30) LogA';...
	'PECy5(676/29) LogH';'PECy5(676/29) LogA';...
	'APC(676/29) LogH';'APC(676/29) LogA';...
	'PECy5.5(690/40) LogH';'PECy5.5(690/40) LogA';...
	'ALexa700(690/40) LogH';'ALexa700(690/40) LogA';...
	'PECy7(740LP) LogH';'PECy7(740LP) LogA';...
	'APCCy7(740LP) LogH';'APCCy7(740LP) LogA';...
	'PACB(445/60) LogH';'PACB(445/60) LogA';...
	'Width';'Time'};

nicknames = {'';'fsc';...
    '';'ssc';...
    'yfp';'';...
    'cfp';'';...
    '';'';...
    '';'';...
    '';'';...
    'mch';'';...
	'';'';...
	'';'';...
	'';'';...
	'';'';...
	'';'';...
	'';'';...
	'bfp';'';...
	'';'t'};

if nargin == 0
    % display default conversions
    disp('Default nicknames and parameter names for Stratedigm:');
    disp({'Nickname','Parameter'});
    disp([nicknames,paramnames]);
else
    % return struct with nickname conversions
    if nargin < 2;
        reverse = false;
    end
    
    paramstruct = struct;
    
    if ~reverse
        % return struct with nicknames -> param names
        if ~isempty(paramstoconvert)
            % find user-supplied nicknames and return conversions
            for c = 1:length(paramstoconvert)
                k = find(strcmp(paramstoconvert{c},nicknames));
                if ~isempty(k)
                    paramstruct.(nicknames{k}) = paramnames{k};
                end
            end
        else
            % use default conversions
            for c = 1:length(nicknames)
                if ~isempty(nicknames{c})
                    paramstruct.(nicknames{c}) = paramnames{c};
                end
            end
        end
    else
        % return struct with param names -> nicknames
        if ~isempty(paramstoconvert)
            % find user-supplied param names and return nicknames
            for c = 1:length(paramstoconvert)
                k = find(strcmp(paramstoconvert{c},nicknames));
                if ~isempty(k)
                    paramstruct.(underscorify(paramnames{k})) = nicknames{k};
                end
            end
        else
            % use default conversions
            for c = 1:length(paramnames)
                if ~isempty(paramnames{c})
                    paramstruct.(underscorify(paramnames{c})) = nicknames{c};
                end
            end
        end
    end
end
    